import { COMPANIES, SKILLS } from "./constants";
import { ExperienceData } from "./types";

export const experienceData: ExperienceData[] = [
  {
    role: "Frontend Engineer",
    company: COMPANIES.MOOV,
    description:
      "Built and maintained critical features across the entire marketplace website including enhanced equipment search functionality, equipment management services, and reusable design systems. Integrated third-party APIs to track shipments, insights on user behavior, and real-time management of open positions.",
    dateStr: "2022 — 2024",
    link: "https://moov.co/search?search_flow_type=text",
    skills: [
      SKILLS.JAVASCRIPT,
      SKILLS.TYPESCRIPT,
      SKILLS.REACT,
      SKILLS.NEXTJS,
      SKILLS.REDUX,
      SKILLS.EMBERJS,
      SKILLS.GOLANG,
      SKILLS.POSTGRESQL,
      SKILLS.JEST,
      SKILLS.REACT_TESTING_LIBRARY,
      SKILLS.TAILWINDCSS,
      SKILLS.BOOTSTRAP,
      SKILLS.MATERIAL_UI,
      SKILLS.CONTENTFUL,
      SKILLS.STORYBOOK,
      SKILLS.LOOKER,
    ],
  },
  {
    role: "Junior Software Engineer",
    company: "Moov Technologies Inc.",
    description:
      "Collaborated with engineering mentor to develop v2.0 of the marketplace website from the ground up and led efforts to enhance website accessibility. Created a blogging system to allow real-time posts and updates. Developed features and data visualizations for the marketplace and internal sales management tool.",
    dateStr: "2020 — 2022",
    link: "https://moov.co/sell",
    skills: [
      SKILLS.JAVASCRIPT,
      SKILLS.TYPESCRIPT,
      SKILLS.REACT,
      SKILLS.NEXTJS,
      SKILLS.REDUX,
      SKILLS.EMBERJS,
      SKILLS.GOLANG,
      SKILLS.POSTGRESQL,
      SKILLS.JEST,
      SKILLS.REACT_TESTING_LIBRARY,
      SKILLS.TAILWINDCSS,
      SKILLS.BOOTSTRAP,
      SKILLS.MATERIAL_UI,
      SKILLS.CONTENTFUL,
      SKILLS.METABASE,
    ],
  },
  {
    role: "Intern Software Engineer",
    company: "Moov Technologies Inc.",
    description:
      "Built user interfaces and enhanced features for a B2B marketplace website and internal sales management tool, enabling our sales team to assist clients in buying and selling used semi-conductor equipment.",
    dateStr: "2020",
    link: "https://www.moov.co",
    skills: [
      SKILLS.JAVASCRIPT,
      SKILLS.REACT,
      SKILLS.NEXTJS,
      SKILLS.REDUX,
      SKILLS.EMBERJS,
      SKILLS.GOLANG,
      SKILLS.POSTGRESQL,
      SKILLS.SASS,
      SKILLS.STYLED_COMPONENTS,
    ],
  },
];
